# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: app
  template:
    metadata:
      labels:
        app: airflow
        tier: app
    spec:
      containers:
      - image: localhost:5000/airflow-sandbox:0.1.0
        name: airflow-sandbox
        env:
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            value: postgresql://airflow:airflow_password@postgres/airflow
        ports:
        - containerPort: 8080
          protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30050
  selector:
    app: airflow
  type: LoadBalancer
